name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: unbuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} envent. "
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your respository is ${{ github.repository code
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo " The ${{ github.respository }} respository has been cloned to the runner."
      - run: echo " The workflow is now ready to test your code on the runner."
      - name: List file in repository
        run: |
          ls ${{ github.workspace }}
      - run: echo " This job's status is ${{ job.status }}."
      
      
